pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'php:8.3.8-alpine3.20' }
      }
      steps {
        sh 'php --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'ruby:3.1.6-alpine3.20' }
      }
      steps {
        sh 'ruby --version'
      }
    }
     stage('db') {
      agent {
        docker { image 'python:3.11-alpine3.20'  }
      }
      steps {
        sh 'python --version'
      }
    }
    stage('database') {
      agent {
        docker { image 'postgres:16.3-alpine3.19'  }
      }
      steps {
        sh 'postgres --version'
      }
    }
    stage('tabledatabase') {
      agent {
        docker { image 'mysql:8-oraclelinux9'  }
      }
      steps {
        sh 'mysql --version'
      }
    }
    stage('data platform for caching') {
      agent {
        docker { image 'redis:7.4-rc1-alpine3.20'  }
      }
      steps {
        sh 'redis --version'
      }
    }
    stage('go imperative programming language') {
      agent {
        docker { image 'golang:1.23rc1-bullseye'  }
      }
      steps {
        sh 'golang --version'
      }
    }

    
  }
}

