pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'php:8.3.8-alpine3.20' }
      }
      steps {
        sh 'php --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'ruby:3.1.6-alpine3.20' }
      }
      steps {
        sh 'ruby --version'
      }
    }
     stage('db') {
      agent {
        docker { image 'python:3.11-alpine3.20'  }
      }
      steps {
        sh 'python --version'
      }
    }
    stage('database') {
      agent {
        docker { image 'redis:7.2.5-alpine3.20'  }
      }
      steps {
        sh 'redis --version'
      }
    }
  }
}

