pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
     stage('production') {
      agent { docker { image 'ruby:3.3.3-alpine3.20' } 
            }
         steps {
                sh 'ruby --version'
                }
     }
  }
}
